version: '3.8'

services:
  api:
    build: .
    container_name: api-automatica
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}